_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 8
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.7
            "8":
                - 1
                - 5
            "12": 0.19.7
            "13": linux-x86_64
gamma:
    value: 0.7472728739749103
learning_rate:
    value: 0.029201573787174473
max_depth:
    value: 5
n_estimators:
    value: 425
subsample:
    value: 0.7536954281783523
