
const wzstudy_images = [
    'FedericaCut_dphi_met_ph - dphi_met_central_jet_0.png',
    'FedericaCut_dphi_met_ph - dphi_met_central_jet_1.png',
    'FedericaCut_dphi_met_phterm - dphi_met_jetterm_0.png',
    'FedericaCut_dphi_met_phterm - dphi_met_jetterm_1.png',
    'FedericaCutwRunCut_dphi_met_ph - dphi_met_central_jet_0.png',
    'FedericaCutwRunCut_dphi_met_ph - dphi_met_central_jet_1.png',
    'FedericaCutwRunCut_dphi_met_phterm - dphi_met_jetterm_0.png',
    'FedericaCutwRunCut_dphi_met_phterm - dphi_met_jetterm_1.png',
    'SelectionCut_dphi_met_ph - dphi_met_central_jet_0.png',
    'SelectionCut_dphi_met_ph - dphi_met_central_jet_1.png',
    'SelectionCut_dphi_met_phterm - dphi_met_jetterm_0.png',
    'SelectionCut_dphi_met_phterm - dphi_met_jetterm_1.png'
];

const d_images = [
    ['ggHyyd_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_basic.png',
    'Wgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_basic.png',
    'Zgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_basic.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_met_jetterm_logZ_basic.png',
    'Wgamma_dphi_met_phterm_vs_dphi_met_jetterm_logZ_basic.png',
    'Zgamma_dphi_met_phterm_vs_dphi_met_jetterm_logZ_basic.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_basic.png',
    'Wgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_basic.png',
    'Zgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_basic.png',],

    ['ggHyyd_dphi_met_jetterm_vs_dphi_phterm_jetterm_noLogZ_basic.png',
    'Wgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_noLogZ_basic.png',
    'Zgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_noLogZ_basic.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_met_jetterm_noLogZ_basic.png',
    'Wgamma_dphi_met_phterm_vs_dphi_met_jetterm_noLogZ_basic.png',
    'Zgamma_dphi_met_phterm_vs_dphi_met_jetterm_noLogZ_basic.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_phterm_jetterm_noLogZ_basic.png',
    'Wgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_noLogZ_basic.png',
    'Zgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_noLogZ_basic.png',],

    ['ggHyyd_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_basic_80.png',
    'Wgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_basic_80.png',
    'Zgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_basic_80.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_met_jetterm_logZ_basic_80.png',
    'Wgamma_dphi_met_phterm_vs_dphi_met_jetterm_logZ_basic_80.png',
    'Zgamma_dphi_met_phterm_vs_dphi_met_jetterm_logZ_basic_80.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_basic_80.png',
    'Wgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_basic_80.png',
    'Zgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_basic_80.png',],

    ['ggHyyd_dphi_met_jetterm_vs_dphi_phterm_jetterm_noLogZ_basic_80.png',
    'Wgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_noLogZ_basic_80.png',
    'Zgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_noLogZ_basic_80.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_met_jetterm_noLogZ_basic_80.png',
    'Wgamma_dphi_met_phterm_vs_dphi_met_jetterm_noLogZ_basic_80.png',
    'Zgamma_dphi_met_phterm_vs_dphi_met_jetterm_noLogZ_basic_80.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_phterm_jetterm_noLogZ_basic_80.png',
    'Wgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_noLogZ_basic_80.png',
    'Zgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_noLogZ_basic_80.png',],

    ['ggHyyd_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_selection.png',
    'Wgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_selection.png',
    'Zgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_selection.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_met_jetterm_logZ_selection.png',
    'Wgamma_dphi_met_phterm_vs_dphi_met_jetterm_logZ_selection.png',
    'Zgamma_dphi_met_phterm_vs_dphi_met_jetterm_logZ_selection.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_selection.png',
    'Wgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_selection.png',
    'Zgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_selection.png',
    'dphi_met_jetterm_vs_dphi_phterm_jetterm_scatter_selection.png',
    'dphi_met_phterm_vs_dphi_met_jetterm_scatter_selection.png',
    'dphi_met_phterm_vs_dphi_phterm_jetterm_scatter_selection.png'],

    ['ggHyyd_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_n-2.png',
    'Wgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_n-2.png',
    'Zgamma_dphi_met_jetterm_vs_dphi_phterm_jetterm_logZ_n-2.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_met_jetterm_logZ_n-2.png',
    'Wgamma_dphi_met_phterm_vs_dphi_met_jetterm_logZ_n-2.png',
    'Zgamma_dphi_met_phterm_vs_dphi_met_jetterm_logZ_n-2.png',
    'ggHyyd_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_n-2.png',
    'Wgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_n-2.png',
    'Zgamma_dphi_met_phterm_vs_dphi_phterm_jetterm_logZ_n-2.png',
    'dphi_met_jetterm_vs_dphi_phterm_jetterm_scatter_n-2.png',
    'dphi_met_phterm_vs_dphi_met_jetterm_scatter_n-2.png',
    'dphi_met_phterm_vs_dphi_phterm_jetterm_scatter_n-2.png'],

    ['vector_plot_met_ph_jet_ggHyyd_event0.png',
    'vector_plot_met_phterm_jetterm_ggHyyd_event0.png',
    'vector_plot_met_ph_jet_ggHyyd_event1.png',
    'vector_plot_met_phterm_jetterm_ggHyyd_event1.png',
    'vector_plot_met_ph_jet_ggHyyd_event2.png',
    'vector_plot_met_phterm_jetterm_ggHyyd_event2.png',
    'vector_plot_met_ph_jet_ggHyyd_event3.png',
    'vector_plot_met_phterm_jetterm_ggHyyd_event3.png',
    'vector_plot_met_ph_jet_ggHyyd_event4.png',
    'vector_plot_met_phterm_jetterm_ggHyyd_event5.png',
    'vector_plot_met_ph_jet_ggHyyd_event6.png',
    'vector_plot_met_phterm_jetterm_ggHyyd_event6.png',
    'vector_plot_met_ph_jet_ggHyyd_event7.png',
    'vector_plot_met_phterm_jetterm_ggHyyd_event7.png',
    'vector_plot_met_ph_jet_ggHyyd_event8.png',
    'vector_plot_met_phterm_jetterm_ggHyyd_event8.png',
    'vector_plot_met_ph_jet_ggHyyd_event9.png',
    'vector_plot_met_phterm_jetterm_ggHyyd_event9.png'],

    ['vector_plot_met_ph_jet_Wgamma_event1.png',   'vector_plot_met_phterm_jetterm_Wgamma_event1.png',
        'vector_plot_met_ph_jet_Wgamma_event2.png',  'vector_plot_met_phterm_jetterm_Wgamma_event2.png',
        'vector_plot_met_ph_jet_Wgamma_event3.png',   'vector_plot_met_phterm_jetterm_Wgamma_event3.png',
        'vector_plot_met_ph_jet_Wgamma_event5.png',   'vector_plot_met_phterm_jetterm_Wgamma_event5.png',
        'vector_plot_met_ph_jet_Wgamma_event6.png',   'vector_plot_met_phterm_jetterm_Wgamma_event6.png',
        'vector_plot_met_ph_jet_Wgamma_event7.png',   'vector_plot_met_phterm_jetterm_Wgamma_event7.png',
        'vector_plot_met_ph_jet_Wgamma_event8.png',   'vector_plot_met_phterm_jetterm_Wgamma_event8.png',
        'vector_plot_met_ph_jet_Wgamma_event9.png',   'vector_plot_met_phterm_jetterm_Wgamma_event9.png',
        'vector_plot_met_ph_jet_Wgamma_event10.png',   'vector_plot_met_phterm_jetterm_Wgamma_event10.png',
        'vector_plot_met_ph_jet_Wgamma_event11.png',   'vector_plot_met_phterm_jetterm_Wgamma_event11.png'],

    ['vector_plot_met_ph_jet_Zgamma_event0.png',  'vector_plot_met_phterm_jetterm_Zgamma_event0.png',
        'vector_plot_met_ph_jet_Zgamma_event1.png',  'vector_plot_met_phterm_jetterm_Zgamma_event1.png',
        'vector_plot_met_ph_jet_Zgamma_event2.png',  'vector_plot_met_phterm_jetterm_Zgamma_event2.png',
        'vector_plot_met_ph_jet_Zgamma_event3.png',  'vector_plot_met_phterm_jetterm_Zgamma_event3.png',
        'vector_plot_met_ph_jet_Zgamma_event4.png',  'vector_plot_met_phterm_jetterm_Zgamma_event4.png',
        'vector_plot_met_ph_jet_Zgamma_event5.png',  'vector_plot_met_phterm_jetterm_Zgamma_event5.png',
        'vector_plot_met_ph_jet_Zgamma_event6.png',  'vector_plot_met_phterm_jetterm_Zgamma_event6.png',
        'vector_plot_met_ph_jet_Zgamma_event7.png',  'vector_plot_met_phterm_jetterm_Zgamma_event7.png',
        'vector_plot_met_ph_jet_Zgamma_event8.png',  'vector_plot_met_phterm_jetterm_Zgamma_event8.png',
        'vector_plot_met_ph_jet_Zgamma_event9.png',  'vector_plot_met_phterm_jetterm_Zgamma_event9.png']
];

const abs_weight_selection_images = [
'mc23d_balancecut/vtx_sumPt_nodijet.png',
'mc23d_abs_weight_selectioncut/vtx_sumPt_absWeightSelection.png',
'mc23d_balancecut/n_ph_nodijet.png',
'mc23d_abs_weight_selectioncut/n_ph_absWeightSelection.png',
'mc23d_balancecut/n_ph_baseline_nodijet.png',
'mc23d_abs_weight_selectioncut/n_ph_baseline_absWeightSelection.png',
'mc23d_balancecut/n_el_baseline_nodijet.png',
'mc23d_abs_weight_selectioncut/n_el_baseline_absWeightSelection.png',
'mc23d_balancecut/n_mu_baseline_nodijet.png',
'mc23d_abs_weight_selectioncut/n_mu_baseline_absWeightSelection.png',
'mc23d_balancecut/n_tau_baseline_nodijet.png',
'mc23d_abs_weight_selectioncut/n_tau_baseline_absWeightSelection.png',
'mc23d_balancecut/puWeight_nodijet.png',
'mc23d_abs_weight_selectioncut/puWeight_absWeightSelection.png',
'mc23d_balancecut/actualIntPerXing_nodijet.png',
'mc23d_abs_weight_selectioncut/actualIntPerXing_absWeightSelection.png',
'mc23d_balancecut/mt_nodijet.png',
'mc23d_abs_weight_selectioncut/mt_absWeightSelection.png',
'mc23d_balancecut/metsig_nodijet.png',
'mc23d_abs_weight_selectioncut/metsig_absWeightSelection.png',
'mc23d_balancecut/metsigres_nodijet.png',
'mc23d_abs_weight_selectioncut/metsigres_absWeightSelection.png',
'mc23d_balancecut/met_nodijet.png',
'mc23d_abs_weight_selectioncut/met_absWeightSelection.png',
'mc23d_balancecut/met_noJVT_nodijet.png',
'mc23d_abs_weight_selectioncut/met_noJVT_absWeightSelection.png',
'mc23d_balancecut/met_cst_nodijet.png',
'mc23d_abs_weight_selectioncut/met_cst_absWeightSelection.png',
'mc23d_balancecut/met_track_nodijet.png',
'mc23d_abs_weight_selectioncut/met_track_absWeightSelection.png',
'mc23d_balancecut/dmet_nodijet.png',
'mc23d_abs_weight_selectioncut/dmet_absWeightSelection.png',
'mc23d_balancecut/ph_pt_nodijet.png',
'mc23d_abs_weight_selectioncut/ph_pt_absWeightSelection.png',
'mc23d_balancecut/ph_eta_nodijet.png',
'mc23d_abs_weight_selectioncut/ph_eta_absWeightSelection.png',
'mc23d_balancecut/ph_phi_nodijet.png',
'mc23d_abs_weight_selectioncut/ph_phi_absWeightSelection.png',
'mc23d_balancecut/jet_central_eta_nodijet.png',
'mc23d_abs_weight_selectioncut/jet_central_eta_absWeightSelection.png',
'mc23d_balancecut/jet_central_pt1_nodijet.png',
'mc23d_abs_weight_selectioncut/jet_central_pt1_absWeightSelection.png',
'mc23d_balancecut/jet_central_pt2_nodijet.png',
'mc23d_abs_weight_selectioncut/jet_central_pt2_absWeightSelection.png',
'mc23d_balancecut/jet_central_pt_nodijet.png',
'mc23d_abs_weight_selectioncut/jet_central_pt_absWeightSelection.png',
'mc23d_balancecut/dphi_met_phterm_nodijet.png',
'mc23d_abs_weight_selectioncut/dphi_met_phterm_absWeightSelection.png',
'mc23d_balancecut/dphi_met_ph_nodijet.png',
'mc23d_abs_weight_selectioncut/dphi_met_ph_absWeightSelection.png',
'mc23d_balancecut/dphi_met_jetterm_nodijet.png',
'mc23d_abs_weight_selectioncut/dphi_met_jetterm_absWeightSelection.png',
'mc23d_balancecut/dphi_phterm_jetterm_nodijet.png',
'mc23d_abs_weight_selectioncut/dphi_phterm_jetterm_absWeightSelection.png',
'mc23d_balancecut/dphi_ph_centraljet1_nodijet.png',
'mc23d_abs_weight_selectioncut/dphi_ph_centraljet1_absWeightSelection.png',
'mc23d_balancecut/dphi_ph_jet1_nodijet.png',
'mc23d_abs_weight_selectioncut/dphi_ph_jet1_absWeightSelection.png',
'mc23d_balancecut/metplusph_nodijet.png',
'mc23d_abs_weight_selectioncut/metplusph_absWeightSelection.png',
'mc23d_balancecut/failJVT_jet_pt_nodijet.png',
'mc23d_abs_weight_selectioncut/failJVT_jet_pt_absWeightSelection.png',
'mc23d_balancecut/failJVT_jet_pt1_nodijet.png',
'mc23d_abs_weight_selectioncut/failJVT_jet_pt1_absWeightSelection.png',
'mc23d_balancecut/softerm_nodijet.png',
'mc23d_abs_weight_selectioncut/softerm_absWeightSelection.png',
'mc23d_balancecut/jetterm_nodijet.png',
'mc23d_abs_weight_selectioncut/jetterm_absWeightSelection.png',
'mc23d_balancecut/jetterm_sumet_nodijet.png',
'mc23d_abs_weight_selectioncut/jetterm_sumet_absWeightSelection.png',
'mc23d_balancecut/n_jet_nodijet.png',
'mc23d_abs_weight_selectioncut/n_jet_absWeightSelection.png',
'mc23d_balancecut/n_jet_central_nodijet.png',
'mc23d_abs_weight_selectioncut/n_jet_central_absWeightSelection.png',
'mc23d_balancecut/n_jet_fwd_nodijet.png',
'mc23d_abs_weight_selectioncut/n_jet_fwd_absWeightSelection.png',
'mc23d_balancecut/goodPV_nodijet.png',
'mc23d_abs_weight_selectioncut/goodPV_absWeightSelection.png',
'mc23d_balancecut/dphi_met_central_jet_nodijet.png',
'mc23d_abs_weight_selectioncut/dphi_met_central_jet_absWeightSelection.png',
'mc23d_balancecut/jet_central_timing1_nodijet.png',
'mc23d_abs_weight_selectioncut/jet_central_timing1_absWeightSelection.png',
'mc23d_balancecut/jet_central_timing_nodijet.png',
'mc23d_abs_weight_selectioncut/jet_central_timing_absWeightSelection.png',
'mc23d_balancecut/jet_central_emfrac_nodijet.png',
'mc23d_abs_weight_selectioncut/jet_central_emfrac_absWeightSelection.png',
'mc23d_balancecut/balance_nodijet.png',
'mc23d_abs_weight_selectioncut/balance_absWeightSelection.png',
'mc23d_balancecut/balance_sumet_nodijet.png',
'mc23d_abs_weight_selectioncut/balance_sumet_absWeightSelection.png',
'mc23d_balancecut/central_jets_fraction_nodijet.png',
'mc23d_abs_weight_selectioncut/central_jets_fraction_absWeightSelection.png',
'mc23d_balancecut/trigger_nodijet.png',
'mc23d_abs_weight_selectioncut/trigger_absWeightSelection.png',
'mc23d_balancecut/dphi_jj_nodijet.png',
'mc23d_abs_weight_selectioncut/dphi_jj_absWeightSelection.png',
'mc23d_balancecut/BDTScore_nodijet.png',
'mc23d_abs_weight_selectioncut/BDTScore_absWeightSelection.png',
];

const abs_weight_basic_images = [
'mc23d_basiccut/vtx_sumPt_nodijet.png',
'mc23d_abs_weight_basiccut/vtx_sumPt_absWeightBasic.png',
'mc23d_basiccut/n_ph_nodijet.png',
'mc23d_abs_weight_basiccut/n_ph_absWeightBasic.png',
'mc23d_basiccut/n_ph_baseline_nodijet.png',
'mc23d_abs_weight_basiccut/n_ph_baseline_absWeightBasic.png',
'mc23d_basiccut/n_el_baseline_nodijet.png',
'mc23d_abs_weight_basiccut/n_el_baseline_absWeightBasic.png',
'mc23d_basiccut/n_mu_baseline_nodijet.png',
'mc23d_abs_weight_basiccut/n_mu_baseline_absWeightBasic.png',
'mc23d_basiccut/n_tau_baseline_nodijet.png',
'mc23d_abs_weight_basiccut/n_tau_baseline_absWeightBasic.png',
'mc23d_basiccut/puWeight_nodijet.png',
'mc23d_abs_weight_basiccut/puWeight_absWeightBasic.png',
'mc23d_basiccut/actualIntPerXing_nodijet.png',
'mc23d_abs_weight_basiccut/actualIntPerXing_absWeightBasic.png',
'mc23d_basiccut/mt_nodijet.png',
'mc23d_abs_weight_basiccut/mt_absWeightBasic.png',
'mc23d_basiccut/metsig_nodijet.png',
'mc23d_abs_weight_basiccut/metsig_absWeightBasic.png',
'mc23d_basiccut/metsigres_nodijet.png',
'mc23d_abs_weight_basiccut/metsigres_absWeightBasic.png',
'mc23d_basiccut/met_nodijet.png',
'mc23d_abs_weight_basiccut/met_absWeightBasic.png',
'mc23d_basiccut/met_noJVT_nodijet.png',
'mc23d_abs_weight_basiccut/met_noJVT_absWeightBasic.png',
'mc23d_basiccut/met_cst_nodijet.png',
'mc23d_abs_weight_basiccut/met_cst_absWeightBasic.png',
'mc23d_basiccut/met_track_nodijet.png',
'mc23d_abs_weight_basiccut/met_track_absWeightBasic.png',
'mc23d_basiccut/dmet_nodijet.png',
'mc23d_abs_weight_basiccut/dmet_absWeightBasic.png',
'mc23d_basiccut/ph_pt_nodijet.png',
'mc23d_abs_weight_basiccut/ph_pt_absWeightBasic.png',
'mc23d_basiccut/ph_eta_nodijet.png',
'mc23d_abs_weight_basiccut/ph_eta_absWeightBasic.png',
'mc23d_basiccut/ph_phi_nodijet.png',
'mc23d_abs_weight_basiccut/ph_phi_absWeightBasic.png',
'mc23d_basiccut/jet_central_eta_nodijet.png',
'mc23d_abs_weight_basiccut/jet_central_eta_absWeightBasic.png',
'mc23d_basiccut/jet_central_pt1_nodijet.png',
'mc23d_abs_weight_basiccut/jet_central_pt1_absWeightBasic.png',
'mc23d_basiccut/jet_central_pt2_nodijet.png',
'mc23d_abs_weight_basiccut/jet_central_pt2_absWeightBasic.png',
'mc23d_basiccut/jet_central_pt_nodijet.png',
'mc23d_abs_weight_basiccut/jet_central_pt_absWeightBasic.png',
'mc23d_basiccut/dphi_met_phterm_nodijet.png',
'mc23d_abs_weight_basiccut/dphi_met_phterm_absWeightBasic.png',
'mc23d_basiccut/dphi_met_ph_nodijet.png',
'mc23d_abs_weight_basiccut/dphi_met_ph_absWeightBasic.png',
'mc23d_basiccut/dphi_met_jetterm_nodijet.png',
'mc23d_abs_weight_basiccut/dphi_met_jetterm_absWeightBasic.png',
'mc23d_basiccut/dphi_phterm_jetterm_nodijet.png',
'mc23d_abs_weight_basiccut/dphi_phterm_jetterm_absWeightBasic.png',
'mc23d_basiccut/dphi_ph_centraljet1_nodijet.png',
'mc23d_abs_weight_basiccut/dphi_ph_centraljet1_absWeightBasic.png',
'mc23d_basiccut/dphi_ph_jet1_nodijet.png',
'mc23d_abs_weight_basiccut/dphi_ph_jet1_absWeightBasic.png',
'mc23d_basiccut/metplusph_nodijet.png',
'mc23d_abs_weight_basiccut/metplusph_absWeightBasic.png',
'mc23d_basiccut/failJVT_jet_pt_nodijet.png',
'mc23d_abs_weight_basiccut/failJVT_jet_pt_absWeightBasic.png',
'mc23d_basiccut/failJVT_jet_pt1_nodijet.png',
'mc23d_abs_weight_basiccut/failJVT_jet_pt1_absWeightBasic.png',
'mc23d_basiccut/softerm_nodijet.png',
'mc23d_abs_weight_basiccut/softerm_absWeightBasic.png',
'mc23d_basiccut/jetterm_nodijet.png',
'mc23d_abs_weight_basiccut/jetterm_absWeightBasic.png',
'mc23d_basiccut/jetterm_sumet_nodijet.png',
'mc23d_abs_weight_basiccut/jetterm_sumet_absWeightBasic.png',
'mc23d_basiccut/n_jet_nodijet.png',
'mc23d_abs_weight_basiccut/n_jet_absWeightBasic.png',
'mc23d_basiccut/n_jet_central_nodijet.png',
'mc23d_abs_weight_basiccut/n_jet_central_absWeightBasic.png',
'mc23d_basiccut/n_jet_fwd_nodijet.png',
'mc23d_abs_weight_basiccut/n_jet_fwd_absWeightBasic.png',
'mc23d_basiccut/goodPV_nodijet.png',
'mc23d_abs_weight_basiccut/goodPV_absWeightBasic.png',
'mc23d_basiccut/dphi_met_central_jet_nodijet.png',
'mc23d_abs_weight_basiccut/dphi_met_central_jet_absWeightBasic.png',
'mc23d_basiccut/jet_central_timing1_nodijet.png',
'mc23d_abs_weight_basiccut/jet_central_timing1_absWeightBasic.png',
'mc23d_basiccut/jet_central_timing_nodijet.png',
'mc23d_abs_weight_basiccut/jet_central_timing_absWeightBasic.png',
'mc23d_basiccut/jet_central_emfrac_nodijet.png',
'mc23d_abs_weight_basiccut/jet_central_emfrac_absWeightBasic.png',
'mc23d_basiccut/balance_nodijet.png',
'mc23d_abs_weight_basiccut/balance_absWeightBasic.png',
'mc23d_basiccut/balance_sumet_nodijet.png',
'mc23d_abs_weight_basiccut/balance_sumet_absWeightBasic.png',
'mc23d_basiccut/central_jets_fraction_nodijet.png',
'mc23d_abs_weight_basiccut/central_jets_fraction_absWeightBasic.png',
'mc23d_basiccut/trigger_nodijet.png',
'mc23d_abs_weight_basiccut/trigger_absWeightBasic.png',
'mc23d_basiccut/dphi_jj_nodijet.png',
'mc23d_abs_weight_basiccut/dphi_jj_absWeightBasic.png',
'mc23d_basiccut/BDTScore_nodijet.png',
'mc23d_abs_weight_basiccut/BDTScore_absWeightBasic.png',
];

const compare_images = [
    "actualIntPerXing_basic_.png",
"actualIntPerXing_nodijet.png",
"balance_basic_.png",
"balance_nodijet.png",
"balance_sumet_basic_.png",
"balance_sumet_nodijet.png",
"central_jets_fraction_basic_.png",
"central_jets_fraction_nodijet.png",
"dmet_basic_.png",
"dmet_nodijet.png",
"dphi_jj_basic_.png",
"dphi_jj_nodijet.png",
"dphi_met_central_jet_basic_.png",
"dphi_met_central_jet_nodijet.png",
"dphi_met_jetterm_basic_.png",
"dphi_met_jetterm_nodijet.png",
"dphi_met_ph_basic_.png",
"dphi_met_ph_nodijet.png",
"dphi_met_phterm_basic_.png",
"dphi_met_phterm_nodijet.png",
"dphi_ph_centraljet1_basic_.png",
"dphi_ph_centraljet1_nodijet.png",
"dphi_ph_jet1_basic_.png",
"dphi_ph_jet1_nodijet.png",
"dphi_phterm_jetterm_basic_.png",
"dphi_phterm_jetterm_nodijet.png",
"failJVT_jet_pt1_basic_.png",
"failJVT_jet_pt1_nodijet.png",
"failJVT_jet_pt_basic_.png",
"failJVT_jet_pt_nodijet.png",
"goodPV_basic_.png",
"goodPV_nodijet.png",
"jet_central_emfrac_basic_.png",
"jet_central_emfrac_nodijet.png",
"jet_central_eta_basic_.png",
"jet_central_eta_nodijet.png",
"jet_central_pt1_basic_.png",
"jet_central_pt1_nodijet.png",
"jet_central_pt2_basic_.png",
"jet_central_pt2_nodijet.png",
"jet_central_pt_basic_.png",
"jet_central_pt_nodijet.png",
"jet_central_timing1_basic_.png",
"jet_central_timing1_nodijet.png",
"jet_central_timing_basic_.png",
"jet_central_timing_nodijet.png",
"jetterm_basic_.png",
"jetterm_nodijet.png",
"jetterm_sumet_basic_.png",
"jetterm_sumet_nodijet.png",
"met_basic_.png",
"met_nodijet.png",
"met_cst_basic_.png",
"met_cst_nodijet.png",
"met_noJVT_basic_.png",
"met_noJVT_nodijet.png",
"metplusph_basic_.png",
"metplusph_nodijet.png",
"metsig_basic_.png",
"metsig_nodijet.png",
"metsigres_basic_.png",
"metsigres_nodijet.png",
"met_track_basic_.png",
"met_track_nodijet.png",
"mt_basic_.png",
"mt_nodijet.png",
"n_el_baseline_basic_.png",
"n_el_baseline_nodijet.png",
"n_jet_basic_.png",
"n_jet_nodijet.png",
"n_jet_central_basic_.png",
"n_jet_central_nodijet.png",
"n_jet_fwd_basic_.png",
"n_jet_fwd_nodijet.png",
"n_mu_baseline_basic_.png",
"n_mu_baseline_nodijet.png",
"n_ph_baseline_basic_.png",
"n_ph_baseline_nodijet.png",
"n_ph_basic_.png",
"n_ph_nodijet.png",
"n_tau_baseline_basic_.png",
"n_tau_baseline_nodijet.png",
"ph_eta_basic_.png",
"ph_eta_nodijet.png",
"ph_phi_basic_.png",
"ph_phi_nodijet.png",
"ph_pt_basic_.png",
"ph_pt_nodijet.png",
"puWeight_basic_.png",
"puWeight_nodijet.png",
"softerm_basic_.png",
"softerm_nodijet.png",
"trigger_basic_.png",
"trigger_nodijet.png",
"vtx_sumPt_basic_.png",
"vtx_sumPt_nodijet.png",
]

const ml_images = [
'sigstudy/mc23d_basiccut/metsig_nodijet.png',
'sigstudy/mc23d_selectioncut/metsig_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/metsig_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/metsig_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_metsig.png',
'sigstudy/mc23d_selectioncut/roc_curve_metsig.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_metsig.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_metsig.png',
'sigstudy/mc23d_basiccut/met_noJVT_nodijet.png',
'sigstudy/mc23d_selectioncut/met_noJVT_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/met_noJVT_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/met_noJVT_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_met_noJVT.png',
'sigstudy/mc23d_selectioncut/roc_curve_met_noJVT.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_met_noJVT.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_met_noJVT.png',
'sigstudy/mc23d_basiccut/dmet_nodijet.png',
'sigstudy/mc23d_selectioncut/dmet_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/dmet_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/dmet_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_dmet.png',
'sigstudy/mc23d_selectioncut/roc_curve_dmet.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_dmet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_dmet.png',
'sigstudy/mc23d_basiccut/dphi_met_phterm_nodijet.png',
'sigstudy/mc23d_selectioncut/dphi_met_phterm_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/dphi_met_phterm_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/dphi_met_phterm_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_dphi_met_phterm.png',
'sigstudy/mc23d_selectioncut/roc_curve_dphi_met_phterm.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_dphi_met_phterm.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_dphi_met_phterm.png',
'sigstudy/mc23d_basiccut/dphi_ph_centraljet1_nodijet.png',
'sigstudy/mc23d_selectioncut/dphi_ph_centraljet1_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/dphi_ph_centraljet1_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/dphi_ph_centraljet1_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_dphi_ph_centraljet1.png',
'sigstudy/mc23d_selectioncut/roc_curve_dphi_ph_centraljet1.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_dphi_ph_centraljet1.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_dphi_ph_centraljet1.png',
'sigstudy/mc23d_basiccut/jetterm_nodijet.png',
'sigstudy/mc23d_selectioncut/jetterm_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/jetterm_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/jetterm_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_jetterm.png',
'sigstudy/mc23d_selectioncut/roc_curve_jetterm.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_jetterm.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_jetterm.png',
'sigstudy/mc23d_basiccut/dphi_met_central_jet_nodijet.png',
'sigstudy/mc23d_selectioncut/dphi_met_central_jet_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/dphi_met_central_jet_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/dphi_met_central_jet_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_dphi_met_central_jet.png',
'sigstudy/mc23d_selectioncut/roc_curve_dphi_met_central_jet.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_dphi_met_central_jet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_dphi_met_central_jet.png',
'sigstudy/mc23d_basiccut/BDTScore_nodijet.png',
'sigstudy/mc23d_selectioncut/BDTScore_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/BDTScore_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/BDTScore_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_BDTScore.png',
'sigstudy/mc23d_selectioncut/roc_curve_BDTScore.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_BDTScore.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_BDTScore.png',
'sigstudy/mc23d_basiccut/metsigres_nodijet.png',
'sigstudy/mc23d_selectioncut/metsigres_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/metsigres_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/metsigres_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_metsigres.png',
'sigstudy/mc23d_selectioncut/roc_curve_metsigres.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_metsigres.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_metsigres.png',
'sigstudy/mc23d_basiccut/ph_pt_nodijet.png',
'sigstudy/mc23d_selectioncut/ph_pt_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/ph_pt_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/ph_pt_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_ph_pt.png',
'sigstudy/mc23d_selectioncut/roc_curve_ph_pt.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_ph_pt.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_ph_pt.png',
'sigstudy/mc23d_basiccut/ph_eta_nodijet.png',
'sigstudy/mc23d_selectioncut/ph_eta_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/ph_eta_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/ph_eta_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_ph_eta.png',
'sigstudy/mc23d_selectioncut/roc_curve_ph_eta.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_ph_eta.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_ph_eta.png',
'sigstudy/mc23d_basiccut/dphi_met_jetterm_nodijet.png',
'sigstudy/mc23d_selectioncut/dphi_met_jetterm_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/dphi_met_jetterm_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/dphi_met_jetterm_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_dphi_met_jetterm.png',
'sigstudy/mc23d_selectioncut/roc_curve_dphi_met_jetterm.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_dphi_met_jetterm.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_dphi_met_jetterm.png',
'sigstudy/mc23d_basiccut/failJVT_jet_pt1_nodijet.png',
'sigstudy/mc23d_selectioncut/failJVT_jet_pt1_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/failJVT_jet_pt1_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/failJVT_jet_pt1_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_failJVT_jet_pt1.png',
'sigstudy/mc23d_selectioncut/roc_curve_failJVT_jet_pt1.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_failJVT_jet_pt1.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_failJVT_jet_pt1.png',
'sigstudy/mc23d_basiccut/n_jet_central_nodijet.png',
'sigstudy/mc23d_selectioncut/n_jet_central_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/n_jet_central_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/n_jet_central_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_n_jet_central.png',
'sigstudy/mc23d_selectioncut/roc_curve_n_jet_central.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_n_jet_central.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_n_jet_central.png',
'sigstudy/mc23d_basiccut/dphi_jj_nodijet.png',
'sigstudy/mc23d_selectioncut/dphi_jj_nodijet.png',
'mlstudy/mc23d_bdt_correlationcut/dphi_jj_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/dphi_jj_nodijet.png',
'sigstudy/mc23d_basiccut/roc_curve_dphi_jj.png',
'sigstudy/mc23d_selectioncut/roc_curve_dphi_jj.png',
'mlstudy/mc23d_bdt_correlationcut/roc_curve_dphi_jj.png',
'mlstudy/mc23d_bdt_nocorrelationcut/roc_curve_dphi_jj.png',
'mlstudy/mc23d_bdt_correlationcut/bdtscore2_nodijet.png',
'mlstudy/mc23d_bdt_nocorrelationcut/bdtscore2_nodijet.png',
]

const imageMap = {
    "phjet": {
        images: wzstudy_images,
        path: 'test/wzstudy',
        imagesPerRow: 2, // Number of images to display per row
        title: 'Study of dphi_met_ph - dphi_met_central_jet'
    },
    "2d": {
        images: d_images,
        path: 'test/2d_plots',
        imagesPerRow: 3,
        title: '2D plots of dphi_met_phterm, dphi_met_jetterm, dphi_met',
        buttons: ['basic_logZ mT>100', 'basic mT>100', 'basic_logZ mT>80', 'basic mT>80', 'selection_logZ', 'n-2_logZ', 'vector_ggHyyd', 'vector_Wgamma', 'vector_Zgamma']
    },
    "absWeightBasic": {
        images: abs_weight_basic_images, 
        path: 'test/lumi135',
        imagesPerRow: 4,
        title: "Performance Plots with absolute weight Comparison (basic cut)"
    },
    "absWeightSelection": {
        images: abs_weight_selection_images, 
        path: 'test/lumi135',
        imagesPerRow: 4,
        title: "Performance Plots with absolute weight Comparison (selection cut)"
    },
    "compare": {
        images: compare_images, 
        path: 'test/compare',
        imagesPerRow: 4,
        title: "Verify the definition of Binomial Exp Z"
    },
    "ml": {
        images: ml_images,
        path: 'test',
        imagesPerRow: 4,
        title: "Image 1: basic cut |  Image 2: selection cut | Image 3: BDTscore (correlation) cut |   Image 4: BDTscore (uncorrelation) cut"
    }
};  