variables = ['run',
 'event',
 'year',
 'averageIntPerXing',
 'actualIntPerXing',
 'trigger_HLT_g50_tight_xe40_cell_xe70_pfopufit_80mTAC_L1eEM26M',
 'n_jet',
 'n_jet_central',
 'n_jet_fwd',
 'n_bjet',
 'n_ph',
 'n_ph_baseline',
 'n_el',
 'n_el_baseline',
 'n_mu',
 'n_mu_baseline',
 'n_tau_baseline',
 'met_tst_sig',
 'failJVT_jet_vecSumPt',
 # 'failJVT_jet_vecSumPhi',
 # 'failJVT_jet_vecSumEta',
 # 'jet_sumPt',
 # 'failJVT_jet_sumPt',
 'jet_central_vecSumPt',
 # 'jet_central_sumPt',
 # 'jet_fwd_vecSumPt',
 # 'jet_fwd_sumPt',
 'el_pt',
 'el_eta',
 'el_phi',
 'n_pv',
 'pv_z',
 'pv_ntracks',
 'vtx_Phi',
 'met_jetterm_et',
 'met_jetterm_phi',
 'met_jetterm_sumet',
 'met_jetterm_noJVT_et',
 'met_jetterm_noJVT_phi',
 'met_jetterm_noJVT_sumet',
 'met_softerm_noJVT_et',
 'met_softerm_noJVT_phi',
 'met_softerm_noJVT_sumet',
 'met_softerm_tst_et',
 'met_softerm_tst_phi',
 'met_softerm_tst_sumet',
 'met_tst_et',
 'met_tst_phi',
 'met_tst_sumet',
 'met_tst_noJVT_et',
 'met_tst_noJVT_phi',
 'met_tst_noJVT_sumet',
 'failJVT_jet_pt',
 'failJVT_jet_eta',
 'failJVT_jet_phi',
 'failJVT_jet_m',
 'failJVT_jet_jvt',
 'failJVT_jet_fjvt',
 'ph_pt',
 'ph_eta',
 'ph_phi',
 'ph_topoetcone40',
 'ph_ZVtx',
 'ph_ZVtx_err',
 'dmet',
 'met_std_et',
 'met_std_phi',
 'dphi_met_jetterm',
 'dphi_met_phterm',
 'dphi_met_eleterm',
 'dphi_central_jj',
 'm_central_jj',
 'central_balance',
 'jet_central_pt',
 'jet_central_eta',
 'jet_central_phi',
 'jet_central_m',
 'BDTScore']


variables_mc = [
 'run',
 'event',
 'year',
 'averageIntPerXing',
 'actualIntPerXing',
 'trigger_HLT_g50_tight_xe40_cell_xe70_pfopufit_80mTAC_L1eEM26M',
 'n_jet',
 'n_jet_central',
 'n_jet_fwd',
 'n_bjet',
 'n_ph',
 'n_ph_baseline',
 'n_el',
 'n_el_baseline',
 'n_mu',
 'n_mu_baseline',
 'n_tau_baseline',
 'met_tst_sig',
'met_tst_et',
 'met_tst_phi',
 'met_tst_sumet',
 'n_pv',
 'pv_z',
 'vtx_Phi',
  'ph_pt',
 'ph_eta',
 'ph_phi',
 'ph_topoetcone40',
 'ph_ZVtx',
 'ph_ZVtx_err',
 'dmet',
 'dphi_met_jetterm',
 'dphi_met_phterm',
 'dphi_central_jj',
 'central_balance',
 'BDTScore',
 'mconly_weight', 'pu_weight', 'jvt_weight', 'mc_weight_sum', 'xsec_ami', 'filter_eff_ami', 'kfactor_ami', 'pv_truth_z']

ntuple_names = ['mc23d_ggHyyd_y', 'mc23d_Zgamma_y', 'mc23d_Wgamma_y', 'mc23d_gammajet_direct_y', 'data23_y', 'data23_eprobe', 'mc23e_ggHyyd_y', 'mc23e_Zgamma_y', 'mc23e_Wgamma_y', 'mc23e_gammajet_direct_y', 'data24_y', 'data24_eprobe'] 
