variables = [
    "actualIntPerXing", "dphi_central_jj", "failJVT_jet_pt", "jet_central_eta",
    "jet_central_phi", "jet_central_pt",
    "met_jetterm_et", "met_jetterm_phi", "met_jetterm_sumet",
    "met_softerm_tst_et", "met_tst_et", "met_tst_noJVT_et", "met_tst_phi",
    "met_tst_sig", "met_tst_noJVT_sig", "n_ph", "n_ph_baseline", "n_el_baseline", "n_mu",
    "n_mu_baseline", "n_jet", "n_jet_central", "n_tau_baseline", "ph_eta",
    "ph_phi", "ph_pt", "pu_weight", "pv_truth_z", "pv_z",
    "trigger_HLT_g50_tight_xe40_cell_xe70_pfopufit_80mTAC_L1eEM26M", "vtx_sumPt",
    "mconly_weight", "mc_weight_sum", "xsec_ami", "filter_eff_ami", "kfactor_ami",
    "pu_weight", "jvt_weight", "event", "ph_topoetcone40", "el_pt", "el_eta", "ph_truth_type", "run",
    "failJVT_jet_vecSumPt", "failJVT_jet_vecSumPhi", "failJVT_jet_vecSumEta", "jet_sumPt", "failJVT_jet_sumPT",
    "vtx_sumPt", "vtx_sumPt2", "vtx_Phi", 
]
variables_data = [
    "actualIntPerXing", "dphi_central_jj", "failJVT_jet_pt", "jet_central_emfrac", "jet_central_eta",
    "jet_central_phi", "jet_central_pt", "jet_central_timing", "met_cst_et",
    "met_jetterm_et", "met_jetterm_phi", "met_jetterm_sumet", "met_phterm_phi",
    "met_softerm_tst_et", "met_tst_et", "met_tst_noJVT_et", "met_tst_phi",
    "met_tst_sig", "met_track_et", "n_ph", "n_ph_baseline", "n_el_baseline",
    "n_mu_baseline", "n_mu", "n_jet", "n_jet_central", "n_tau_baseline", "ph_eta",
    "ph_phi", "ph_pt", "pv_z", "BDTScore",
    "trigger_HLT_g50_tight_xe40_cell_xe70_pfopufit_80mTAC_L1eEM26M", "vtx_sumPt",
    "event", "ph_topoetcone40", "el_pt", "el_eta", "run"
]
ntuple_names = ['ggHyyd','Zjets','Zgamma','Wgamma','Wjets','gammajet_direct','gammajet_frag','dijet']
ntuple_names_BDT = ['ggHyyd','Zjets','Zgamma','Wgamma','Wjets','gammajet_direct','gammajet_frag','dijets']



['run',
 'event',
 'year',
 'averageIntPerXing',
 'actualIntPerXing',
 'trigger_HLT_g50_tight_xe40_cell_xe70_pfopufit_80mTAC_L1eEM26M',
 'mconly_weight',
 'pu_weight',
 'jvt_weight',
 'n_jet',
 'n_jet_central',
 'n_jet_fwd',
 'n_jet_failJVT',
 'n_bjet',
 'n_ph',
 'n_ph_baseline',
 'n_ph_loose',
 'n_el',
 'n_el_baseline',
 'n_mu',
 'n_mu_baseline',
 'n_tau_baseline',
 'met_tst_sig',
 'met_tst_noJVT_sig',
 'jet_vecSumPt',
 'failJVT_jet_vecSumPt',
 'failJVT_jet_vecSumPhi',
 'failJVT_jet_vecSumEta',
 'jet_sumPt',
 'failJVT_jet_sumPt',
 'jet_central_vecSumPt',
 'jet_central_sumPt',
 'jet_fwd_vecSumPt',
 'jet_fwd_sumPt',
 'n_pv',
 'pv_z',
 'pv_truth_z',
 'pv_ntracks',
 'vtx_sumPt',
 'vtx_sumPt2',
 'z_asym',
 'z_kurt',
 'z_skew',
 'vtx_Phi',
 'met_jetterm_et',
 'met_jetterm_phi',
 'met_jetterm_sumet',
 'met_jetterm_noJVT_et',
 'met_jetterm_noJVT_phi',
 'met_jetterm_noJVT_sumet',
 'met_softerm_noJVT_et',
 'met_softerm_noJVT_phi',
 'met_softerm_noJVT_sumet',
 'met_softerm_tst_et',
 'met_softerm_tst_phi',
 'met_softerm_tst_sumet',
 'met_truth_et',
 'met_truth_phi',
 'met_tst_et',
 'met_tst_phi',
 'met_tst_sumet',
 'met_tst_noJVT_et',
 'met_tst_noJVT_phi',
 'met_tst_noJVT_sumet',
 'failJVT_jet_pt',
 'failJVT_jet_eta',
 'failJVT_jet_phi',
 'failJVT_jet_m',
 'failJVT_jet_jvt',
 'failJVT_jet_fjvt',
 'ph_pt',
 'ph_eta',
 'ph_phi',
 'ph_topoetcone40',
 'ph_ZVtx',
 'ph_ZVtx_err',
 'mc_weight_sum',
 'xsec_ami',
 'filter_eff_ami',
 'kfactor_ami',
 'm_uuy',
 'm_uu',
 'm_uue',
 'dmet',
 'met_std_et',
 'met_std_phi',
 'dphi_met_jetterm',
 'dphi_met_phterm',
 'dphi_met_eleterm',
 'dphi_jj',
 'm_jj',
 'dphi_central_jj',
 'm_central_jj',
 'central_balance',
 'jet_central_pt',
 'jet_central_eta',
 'jet_central_phi',
 'jet_central_m',
 'BDTScore']