_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 8
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.7
            "8":
                - 1
                - 5
            "12": 0.19.7
            "13": linux-x86_64
gamma:
    value: 0.7311811739492958
learning_rate:
    value: 0.040214905218462826
max_depth:
    value: 6
n_estimators:
    value: 543
subsample:
    value: 0.430015261148148
