_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 8
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.7
            "8":
                - 1
                - 5
            "12": 0.19.7
            "13": linux-x86_64
gamma:
    value: 0.5458390229210474
learning_rate:
    value: 0.05500555702736201
max_depth:
    value: 8
n_estimators:
    value: 847
subsample:
    value: 0.6430603145173079
