_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 5
                - 6
                - 8
                - 53
                - 54
                - 55
            "2":
                - 5
                - 6
                - 8
                - 53
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.7
            "8":
                - 1
                - 5
            "12": 0.19.7
            "13": linux-x86_64
gamma:
    value: 0.10551241190359065
learning_rate:
    value: 0.03676431697413079
max_depth:
    value: 7
n_estimators:
    value: 680
subsample:
    value: 0.8228334943548083
